code --install-extension dbaeumer.vscode-eslint
code --install-extension dhall.dhall-lang
code --install-extension dhall.vscode-dhall-lsp-server
code --install-extension DigitalAssetHoldingsLLC.ghcide
code --install-extension dzannotti.vscode-babel-coloring
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension GrapeCity.gc-excelviewer
code --install-extension haskell.haskell
code --install-extension hoovercj.haskell-linter
code --install-extension jcanero.hoogle-vscode
code --install-extension justusadam.language-haskell
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension MaxGabriel.brittany
code --install-extension mjmcloug.vscode-elixir
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode.cpptools
code --install-extension mtxr.sqltools
code --install-extension mtxr.sqltools-driver-mysql
code --install-extension nwolverson.ide-purescript
code --install-extension nwolverson.language-purescript
code --install-extension richie5um2.vscode-sort-json
code --install-extension vigoo.stylish-haskell
code --install-extension yzhang.markdown-all-in-one
